import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { motion } from 'framer-motion'
import {
  SparklesIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  PencilIcon,
  ClockIcon,
  AcademicCapIcon,
} from '@heroicons/react/24/outline'
import { Button, Input, ModalFooter, Alert, Badge } from '@/components/ui'
import { apiPost, ApiError } from '@/lib/api'
import type { DifficultyLevel } from '@/types/database'

const generateSchema = z.object({
  goal: z.string().min(10, '研修ゴールを10文字以上で入力してください'),
  targetAudience: z.string().optional(),
  durationMinutes: z
    .number({ invalid_type_error: '数値を入力してください' })
    .min(15, '最小15分以上を設定してください')
    .max(480, '最大480分（8時間）まで設定できます'),
  difficultyLevel: z.enum(['beginner', 'intermediate', 'advanced'] as const),
})

type GenerateFormData = z.infer<typeof generateSchema>

// Structure generated by Opus
interface ChapterStructure {
  order: number
  title: string
  summary: string
  learningObjectives: string[]
  estimatedMinutes: number
}

interface GeneratedStructure {
  name: string
  description: string
  difficultyLevel: DifficultyLevel
  targetAudience: string
  durationMinutes: number
  tags: string[]
  chapters: ChapterStructure[]
}

// Final curriculum with content generated by Sonnet
interface GeneratedChapter {
  order: number
  title: string
  content: string
  taskDescription: string
  estimatedMinutes: number
}

interface GeneratedCurriculum {
  name: string
  description: string
  difficultyLevel: DifficultyLevel
  tags: string[]
  chapters: GeneratedChapter[]
}

interface CurriculumGenerateFormProps {
  onGenerated: (curriculum: GeneratedCurriculum) => void
  onCancel: () => void
}

const DIFFICULTY_LABELS: Record<DifficultyLevel, string> = {
  beginner: '初級',
  intermediate: '中級',
  advanced: '上級',
  mixed: '混合',
}

type Step = 'input' | 'structure' | 'content' | 'complete'

export function CurriculumGenerateForm({ onGenerated, onCancel }: CurriculumGenerateFormProps) {
  const [step, setStep] = useState<Step>('input')
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<GenerateFormData | null>(null)
  const [generatedStructure, setGeneratedStructure] = useState<GeneratedStructure | null>(null)
  const [generatedCurriculum, setGeneratedCurriculum] = useState<GeneratedCurriculum | null>(null)
  const [usageInfo, setUsageInfo] = useState<{ structure?: { tokens: number; model: string }; content?: { tokens: number; model: string } }>({})

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<GenerateFormData>({
    resolver: zodResolver(generateSchema),
    defaultValues: {
      goal: '',
      targetAudience: '企業の一般社員',
      durationMinutes: 60,
      difficultyLevel: 'beginner',
    },
  })

  // Step 1: Generate structure with Opus
  const handleGenerateStructure = async (data: GenerateFormData) => {
    setIsGenerating(true)
    setError(null)
    setFormData(data)

    try {
      const result = await apiPost<{
        structure: GeneratedStructure
        usage: { inputTokens: number; outputTokens: number; model: string }
      }>('generate-curriculum-structure', {
        goal: data.goal,
        targetAudience: data.targetAudience,
        durationMinutes: data.durationMinutes,
        difficultyLevel: data.difficultyLevel,
      })

      setGeneratedStructure(result.structure)
      setUsageInfo({
        structure: {
          tokens: result.usage.inputTokens + result.usage.outputTokens,
          model: 'Claude Sonnet 4.5',
        },
      })
      setStep('structure')
    } catch (err) {
      console.error('Error generating structure:', err)
      if (err instanceof ApiError) {
        setError(err.message)
      } else {
        setError(err instanceof Error ? err.message : '構成生成に失敗しました')
      }
    } finally {
      setIsGenerating(false)
    }
  }

  // Step 2: Generate content with Sonnet (after approval)
  const handleGenerateContent = async () => {
    if (!generatedStructure || !formData) return

    setIsGenerating(true)
    setError(null)
    setStep('content')

    try {
      const result = await apiPost<{
        curriculum: GeneratedCurriculum
        usage: { inputTokens: number; outputTokens: number; model: string }
      }>('generate-curriculum-content', {
        goal: formData.goal,
        targetAudience: generatedStructure.targetAudience,
        difficultyLevel: generatedStructure.difficultyLevel,
        curriculumName: generatedStructure.name,
        curriculumDescription: generatedStructure.description,
        chapters: generatedStructure.chapters,
        tags: generatedStructure.tags,
      })

      setGeneratedCurriculum(result.curriculum)
      setUsageInfo((prev) => ({
        ...prev,
        content: {
          tokens: result.usage.inputTokens + result.usage.outputTokens,
          model: 'Claude Sonnet 4.5',
        },
      }))
      setStep('complete')
    } catch (err) {
      console.error('Error generating content:', err)
      if (err instanceof ApiError) {
        setError(err.message)
      } else {
        setError(err instanceof Error ? err.message : 'コンテンツ生成に失敗しました')
      }
      setStep('structure')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleUseGenerated = () => {
    if (generatedCurriculum) {
      onGenerated(generatedCurriculum)
    }
  }

  const handleRestart = () => {
    setStep('input')
    setGeneratedStructure(null)
    setGeneratedCurriculum(null)
    setUsageInfo({})
    setError(null)
  }

  // Step indicator
  const StepIndicator = () => (
    <div className="flex items-center justify-center gap-2 mb-6">
      {(['input', 'structure', 'content', 'complete'] as Step[]).map((s, index) => (
        <div key={s} className="flex items-center">
          <div
            className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors ${
              step === s
                ? 'bg-primary text-white'
                : ['input', 'structure', 'content', 'complete'].indexOf(step) > index
                  ? 'bg-success text-white'
                  : 'bg-gray-200 text-text-light'
            }`}
          >
            {['input', 'structure', 'content', 'complete'].indexOf(step) > index ? (
              <CheckCircleIcon className="w-5 h-5" />
            ) : (
              index + 1
            )}
          </div>
          {index < 3 && (
            <div
              className={`w-8 h-0.5 ${
                ['input', 'structure', 'content', 'complete'].indexOf(step) > index
                  ? 'bg-success'
                  : 'bg-gray-200'
              }`}
            />
          )}
        </div>
      ))}
    </div>
  )

  // Step 1: Input form
  if (step === 'input') {
    return (
      <form onSubmit={handleSubmit(handleGenerateStructure)} className="space-y-4">
        <StepIndicator />

        <div className="bg-primary-light/50 rounded-lg p-4 flex items-start gap-3">
          <SparklesIcon className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
          <div className="text-sm">
            <p className="font-medium text-text">Step 1: 構成の自動生成</p>
            <p className="text-text-light mt-1">
              Claude Sonnet 4.5 がカリキュラムの構成を設計します。
              構成を確認・承認後、詳細コンテンツを生成します。
            </p>
          </div>
        </div>

        {error && (
          <Alert variant="error" onClose={() => setError(null)}>
            {error}
          </Alert>
        )}

        <div>
          <label className="block text-sm font-medium text-text mb-1.5">
            研修ゴール <span className="text-error">*</span>
          </label>
          <textarea
            className="w-full px-4 py-2.5 border border-border rounded-lg bg-white text-text
              transition-colors duration-200 min-h-[100px]
              focus:outline-none focus:ring-2 focus:ring-offset-0 focus:ring-primary/50 focus:border-primary"
            placeholder="例：生成AIを業務で活用するための基礎知識と実践スキルを習得する"
            {...register('goal')}
          />
          {errors.goal && (
            <p className="mt-1 text-sm text-error">{errors.goal.message}</p>
          )}
        </div>

        <Input
          label="対象者"
          placeholder="企業の一般社員"
          helperText="研修の対象となる受講者の属性を入力してください"
          {...register('targetAudience')}
        />

        <div className="grid grid-cols-2 gap-4">
          <Input
            label="目標所要時間（分）"
            type="number"
            placeholder="60"
            error={errors.durationMinutes?.message}
            {...register('durationMinutes', { valueAsNumber: true })}
          />

          <div>
            <label className="block text-sm font-medium text-text mb-1.5">
              難易度
            </label>
            <select
              className="w-full px-4 py-2.5 border border-border rounded-lg bg-white text-text
                transition-colors duration-200
                focus:outline-none focus:ring-2 focus:ring-offset-0 focus:ring-primary/50 focus:border-primary"
              {...register('difficultyLevel')}
            >
              {(Object.keys(DIFFICULTY_LABELS) as DifficultyLevel[]).map((level) => (
                <option key={level} value={level}>
                  {DIFFICULTY_LABELS[level]}
                </option>
              ))}
            </select>
          </div>
        </div>

        <ModalFooter>
          <Button type="button" variant="ghost" onClick={onCancel}>
            キャンセル
          </Button>
          <Button
            type="submit"
            isLoading={isGenerating}
            leftIcon={!isGenerating ? <SparklesIcon className="w-5 h-5" /> : undefined}
          >
            {isGenerating ? '構成を生成中...' : '構成を生成'}
          </Button>
        </ModalFooter>
      </form>
    )
  }

  // Step 2: Structure review & approval
  if (step === 'structure' && generatedStructure) {
    const totalMinutes = generatedStructure.chapters.reduce((sum, ch) => sum + ch.estimatedMinutes, 0)

    return (
      <div className="space-y-4">
        <StepIndicator />

        <div className="bg-green-50 rounded-lg p-4 flex items-start gap-3">
          <CheckCircleIcon className="w-5 h-5 text-success flex-shrink-0 mt-0.5" />
          <div className="text-sm">
            <p className="font-medium text-text">Step 2: 構成の確認・承認</p>
            <p className="text-text-light mt-1">
              カリキュラム構成が生成されました。内容を確認し、承認するとコンテンツ生成に進みます。
            </p>
          </div>
        </div>

        {error && (
          <Alert variant="error" onClose={() => setError(null)}>
            {error}
          </Alert>
        )}

        <div className="bg-gray-50 rounded-lg p-4 space-y-4">
          {/* Curriculum header */}
          <div>
            <div className="flex items-start justify-between gap-4">
              <h3 className="font-semibold text-lg text-text">{generatedStructure.name}</h3>
              <Badge variant={DIFFICULTY_LABELS[generatedStructure.difficultyLevel] === '初級' ? 'success' : DIFFICULTY_LABELS[generatedStructure.difficultyLevel] === '中級' ? 'warning' : 'error'}>
                {DIFFICULTY_LABELS[generatedStructure.difficultyLevel]}
              </Badge>
            </div>
            <p className="text-sm text-text-light mt-2">{generatedStructure.description}</p>
          </div>

          {/* Meta info */}
          <div className="flex flex-wrap gap-4 text-sm text-text-light">
            <span className="flex items-center gap-1">
              <ClockIcon className="w-4 h-4" />
              合計 {totalMinutes}分
            </span>
            <span className="flex items-center gap-1">
              <AcademicCapIcon className="w-4 h-4" />
              {generatedStructure.chapters.length}チャプター
            </span>
          </div>

          {/* Tags */}
          <div className="flex flex-wrap gap-2">
            {generatedStructure.tags.map((tag) => (
              <span
                key={tag}
                className="px-2 py-1 text-xs bg-primary-light text-primary rounded-full"
              >
                {tag}
              </span>
            ))}
          </div>

          {/* Chapters */}
          <div className="border-t border-border pt-4">
            <h4 className="font-medium text-text mb-3">チャプター構成</h4>
            <div className="space-y-3 max-h-72 overflow-y-auto">
              {generatedStructure.chapters.map((chapter) => (
                <motion.div
                  key={chapter.order}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: chapter.order * 0.05 }}
                  className="p-4 bg-white rounded-lg border border-border"
                >
                  <div className="flex items-start gap-3">
                    <span className="flex-shrink-0 w-7 h-7 flex items-center justify-center bg-primary text-white text-sm font-medium rounded-full">
                      {chapter.order}
                    </span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <p className="font-medium text-text">{chapter.title}</p>
                        <span className="text-xs text-text-light whitespace-nowrap">
                          {chapter.estimatedMinutes}分
                        </span>
                      </div>
                      <p className="text-sm text-text-light mt-1">{chapter.summary}</p>
                      {chapter.learningObjectives.length > 0 && (
                        <div className="mt-2">
                          <p className="text-xs font-medium text-text-light">学習目標:</p>
                          <ul className="mt-1 space-y-0.5">
                            {chapter.learningObjectives.map((obj, i) => (
                              <li key={i} className="text-xs text-text-light flex items-start gap-1">
                                <span className="text-primary">•</span>
                                {obj}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* Usage info */}
        {usageInfo.structure && (
          <p className="text-xs text-text-light text-right">
            構成生成: {usageInfo.structure.model} ({usageInfo.structure.tokens.toLocaleString()} tokens)
          </p>
        )}

        <div className="bg-yellow-50 rounded-lg p-4 flex items-start gap-3">
          <ExclamationTriangleIcon className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-yellow-800">
            <p className="font-medium">承認後の処理</p>
            <p className="mt-1">
              承認すると Claude Sonnet 4.5 が各チャプターの詳細コンテンツを生成します。
              チャプター数に応じて数十秒〜数分かかる場合があります。
            </p>
          </div>
        </div>

        <ModalFooter>
          <Button variant="ghost" onClick={handleRestart}>
            やり直す
          </Button>
          <Button
            onClick={handleGenerateContent}
            leftIcon={<CheckCircleIcon className="w-5 h-5" />}
          >
            構成を承認してコンテンツを生成
          </Button>
        </ModalFooter>
      </div>
    )
  }

  // Step 3: Content generation in progress
  if (step === 'content') {
    return (
      <div className="space-y-4">
        <StepIndicator />

        <div className="text-center py-12">
          <div className="w-16 h-16 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-6" />
          <h3 className="text-lg font-medium text-text mb-2">コンテンツを生成中...</h3>
          <p className="text-text-light">
            Claude Sonnet 4.5 が各チャプターの詳細コンテンツを作成しています。
          </p>
          <p className="text-sm text-text-light mt-2">
            {generatedStructure?.chapters.length || 0}チャプター分のコンテンツを生成中
          </p>
        </div>
      </div>
    )
  }

  // Step 4: Complete - Show final curriculum
  if (step === 'complete' && generatedCurriculum) {
    return (
      <div className="space-y-4">
        <StepIndicator />

        <Alert variant="success">
          カリキュラムの生成が完了しました。内容を確認してください。
        </Alert>

        <div className="bg-gray-50 rounded-lg p-4 space-y-4">
          <div>
            <h3 className="font-semibold text-lg text-text">{generatedCurriculum.name}</h3>
            <p className="text-sm text-text-light mt-1">{generatedCurriculum.description}</p>
          </div>

          <div className="flex flex-wrap gap-2">
            {generatedCurriculum.tags.map((tag) => (
              <span
                key={tag}
                className="px-2 py-1 text-xs bg-primary-light text-primary rounded-full"
              >
                {tag}
              </span>
            ))}
          </div>

          <div className="border-t border-border pt-4">
            <h4 className="font-medium text-text mb-2">
              生成されたチャプター（{generatedCurriculum.chapters.length}章）
            </h4>
            <div className="space-y-2 max-h-64 overflow-y-auto">
              {generatedCurriculum.chapters.map((chapter) => (
                <div
                  key={chapter.order}
                  className="flex items-start gap-3 p-3 bg-white rounded-lg border border-border"
                >
                  <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center bg-success text-white text-xs font-medium rounded-full">
                    <CheckCircleIcon className="w-4 h-4" />
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-sm text-text">{chapter.title}</p>
                    <p className="text-xs text-text-light mt-0.5">
                      約{chapter.estimatedMinutes}分 | コンテンツ生成済み
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Usage info */}
        <div className="text-xs text-text-light text-right space-y-1">
          {usageInfo.structure && (
            <p>構成生成: {usageInfo.structure.model} ({usageInfo.structure.tokens.toLocaleString()} tokens)</p>
          )}
          {usageInfo.content && (
            <p>コンテンツ生成: {usageInfo.content.model} ({usageInfo.content.tokens.toLocaleString()} tokens)</p>
          )}
        </div>

        <ModalFooter>
          <Button variant="ghost" onClick={handleRestart} leftIcon={<PencilIcon className="w-4 h-4" />}>
            最初からやり直す
          </Button>
          <Button onClick={handleUseGenerated}>
            このカリキュラムを使用
          </Button>
        </ModalFooter>
      </div>
    )
  }

  return null
}
